version: '3'

services:
  
  django:
    build: .
    command: sh run.sh
    ports:
      - "80:8000"
    env_file: ./dev.env
    volumes:
      - .:/usr/src/app

  celery:
    build: .
    command: sh run_celery.sh
    env_file: dev.env
    volumes:
      - .:/usr/src/app

  redis:
    image: redis
    ports:
      - "6379:6379"


volumes:  
  db_data:
    external: true
